baseURL = "https://hartmantam.xyz/"
languageCode = "en-us"
title = "(no title)"
theme = "PaperMod"
copyright = "This work is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/)"
enableRobotsTXT = true

[params]
env = "production"
title = "(no title)"
description = "Anything can show up here"
author = ["Hartman"]
keywords = ["blog", "tech", "server", "linux", "windows"]
ShowReadingTime = true
ShowCodeCopyButtons = true
disableSpecial1stPost = true

[params.fuseOpts]
minMatchCharLength = 3
useExtendedSearch = true
keys = ["title", "summary", "content"]

[outputs]
home = ["HTML", "RSS", "JSON"]

[[menu.main]]
name = "Tech"
url = "/tech"

weight = 10

[[menu.main]]
name = "About"
url = "/about"
weight = 20

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 30

[[menu.main]]
name = "Search"
url = "/search"
weight = 90
